LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := hsp3crypt
LOCAL_CFLAGS := -D__ANDROID__ -Wno-narrowing -DHSPNDK -DHSPEMBED -DHSPDISH -DUSE_OBAQ
LOCAL_CPPFLAGS  += -fexceptions
LOCAL_C_INCLUDES += ../hsplib37r1

LOCAL_SRC_FILES := hsp3/hsp3crypt.cpp

include $(BUILD_STATIC_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE    := gameplay
LOCAL_CFLAGS := -D__ANDROID__ -Wno-narrowing -DHSPNDK -DHSPEMBED -DHSPDISH -DHSPDISHGP
LOCAL_CPPFLAGS  += -fexceptions -std=c++11 -frtti -Wno-switch-enum -Wno-switch -Wno-narrowing
LOCAL_ARM_MODE := arm
LOCAL_SHORT_COMMANDS := true

LOCAL_C_INCLUDES += $(LOCAL_PATH)/hsp3dish/gameplay/src
LOCAL_C_INCLUDES += $(LOCAL_PATH)/hsp3dish/extlib/src

LOCAL_SRC_FILES := hsp3/hsp3crypt.cpp \
hsp3dish/gameplay/src/AbsoluteLayout.cpp \
hsp3dish/gameplay/src/AIAgent.cpp \
hsp3dish/gameplay/src/AIController.cpp \
hsp3dish/gameplay/src/AIMessage.cpp \
hsp3dish/gameplay/src/AIState.cpp \
hsp3dish/gameplay/src/AIStateMachine.cpp \
hsp3dish/gameplay/src/Animation.cpp \
hsp3dish/gameplay/src/AnimationClip.cpp \
hsp3dish/gameplay/src/AnimationController.cpp \
hsp3dish/gameplay/src/AnimationTarget.cpp \
hsp3dish/gameplay/src/AnimationValue.cpp \
hsp3dish/gameplay/src/AudioController.cpp \
hsp3dish/gameplay/src/AudioListener.cpp \
hsp3dish/gameplay/src/AudioSource.cpp \
hsp3dish/gameplay/src/BoundingBox.cpp \
hsp3dish/gameplay/src/BoundingSphere.cpp \
hsp3dish/gameplay/src/Bundle.cpp \
hsp3dish/gameplay/src/Button.cpp \
hsp3dish/gameplay/src/Camera.cpp \
hsp3dish/gameplay/src/CheckBox.cpp \
hsp3dish/gameplay/src/Container.cpp \
hsp3dish/gameplay/src/Control.cpp \
hsp3dish/gameplay/src/ControlFactory.cpp \
hsp3dish/gameplay/src/Curve.cpp \
hsp3dish/gameplay/src/DebugNew.cpp \
hsp3dish/gameplay/src/DepthStencilTarget.cpp \
hsp3dish/gameplay/src/Drawable.cpp \
hsp3dish/gameplay/src/Effect.cpp \
hsp3dish/gameplay/src/FileSystem.cpp \
hsp3dish/gameplay/src/FlowLayout.cpp \
hsp3dish/gameplay/src/Font.cpp \
hsp3dish/gameplay/src/Form.cpp \
hsp3dish/gameplay/src/FrameBuffer.cpp \
hsp3dish/gameplay/src/Frustum.cpp \
hsp3dish/gameplay/src/Game.cpp \
hsp3dish/gameplay/src/Gamepad.cpp \
hsp3dish/gameplay/src/HeightField.cpp \
hsp3dish/gameplay/src/Image.cpp \
hsp3dish/gameplay/src/ImageControl.cpp \
hsp3dish/gameplay/src/Joint.cpp \
hsp3dish/gameplay/src/JoystickControl.cpp \
hsp3dish/gameplay/src/Label.cpp \
hsp3dish/gameplay/src/Layout.cpp \
hsp3dish/gameplay/src/Light.cpp \
hsp3dish/gameplay/src/Logger.cpp \
hsp3dish/gameplay/src/Material.cpp \
hsp3dish/gameplay/src/MaterialParameter.cpp \
hsp3dish/gameplay/src/MathUtil.cpp \
hsp3dish/gameplay/src/Matrix.cpp \
hsp3dish/gameplay/src/Mesh.cpp \
hsp3dish/gameplay/src/MeshBatch.cpp \
hsp3dish/gameplay/src/MeshPart.cpp \
hsp3dish/gameplay/src/MeshSkin.cpp \
hsp3dish/gameplay/src/Model.cpp \
hsp3dish/gameplay/src/Node.cpp \
hsp3dish/gameplay/src/ParticleEmitter.cpp \
hsp3dish/gameplay/src/Pass.cpp \
hsp3dish/gameplay/src/PhysicsCharacter.cpp \
hsp3dish/gameplay/src/PhysicsCollisionObject.cpp \
hsp3dish/gameplay/src/PhysicsCollisionShape.cpp \
hsp3dish/gameplay/src/PhysicsConstraint.cpp \
hsp3dish/gameplay/src/PhysicsController.cpp \
hsp3dish/gameplay/src/PhysicsFixedConstraint.cpp \
hsp3dish/gameplay/src/PhysicsGenericConstraint.cpp \
hsp3dish/gameplay/src/PhysicsGhostObject.cpp \
hsp3dish/gameplay/src/PhysicsHingeConstraint.cpp \
hsp3dish/gameplay/src/PhysicsRigidBody.cpp \
hsp3dish/gameplay/src/PhysicsSocketConstraint.cpp \
hsp3dish/gameplay/src/PhysicsSpringConstraint.cpp \
hsp3dish/gameplay/src/PhysicsVehicle.cpp \
hsp3dish/gameplay/src/PhysicsVehicleWheel.cpp \
hsp3dish/gameplay/src/Plane.cpp \
hsp3dish/gameplay/src/Platform.cpp \
hsp3dish/gameplay/src/Properties.cpp \
hsp3dish/gameplay/src/Quaternion.cpp \
hsp3dish/gameplay/src/RadioButton.cpp \
hsp3dish/gameplay/src/Ray.cpp \
hsp3dish/gameplay/src/Rectangle.cpp \
hsp3dish/gameplay/src/Ref.cpp \
hsp3dish/gameplay/src/RenderState.cpp \
hsp3dish/gameplay/src/RenderTarget.cpp \
hsp3dish/gameplay/src/Scene.cpp \
hsp3dish/gameplay/src/SceneLoader.cpp \
hsp3dish/gameplay/src/ScreenDisplayer.cpp \
hsp3dish/gameplay/src/ScriptController.cpp \
hsp3dish/gameplay/src/ScriptTarget.cpp \
hsp3dish/gameplay/src/Slider.cpp \
hsp3dish/gameplay/src/Sprite.cpp \
hsp3dish/gameplay/src/SpriteBatch.cpp \
hsp3dish/gameplay/src/stb_image.cpp \
hsp3dish/gameplay/src/Technique.cpp \
hsp3dish/gameplay/src/Terrain.cpp \
hsp3dish/gameplay/src/TerrainPatch.cpp \
hsp3dish/gameplay/src/Text.cpp \
hsp3dish/gameplay/src/TextBox.cpp \
hsp3dish/gameplay/src/Texture.cpp \
hsp3dish/gameplay/src/Theme.cpp \
hsp3dish/gameplay/src/ThemeStyle.cpp \
hsp3dish/gameplay/src/TileSet.cpp \
hsp3dish/gameplay/src/Transform.cpp \
hsp3dish/gameplay/src/Vector2.cpp \
hsp3dish/gameplay/src/Vector3.cpp \
hsp3dish/gameplay/src/Vector4.cpp \
hsp3dish/gameplay/src/VertexAttributeBinding.cpp \
hsp3dish/gameplay/src/VertexFormat.cpp \
hsp3dish/gameplay/src/VerticalLayout.cpp \
hsp3dish/extlib/src/BulletCollision/BroadphaseCollision/btAxisSweep3.cpp \
hsp3dish/extlib/src/BulletCollision/BroadphaseCollision/btBroadphaseProxy.cpp \
hsp3dish/extlib/src/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.cpp \
hsp3dish/extlib/src/BulletCollision/BroadphaseCollision/btDbvt.cpp \
hsp3dish/extlib/src/BulletCollision/BroadphaseCollision/btDbvtBroadphase.cpp \
hsp3dish/extlib/src/BulletCollision/BroadphaseCollision/btDispatcher.cpp \
hsp3dish/extlib/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp \
hsp3dish/extlib/src/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp \
hsp3dish/extlib/src/BulletCollision/BroadphaseCollision/btSimpleBroadphase.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btBoxBoxDetector.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btCollisionDispatcherMt.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btCollisionObject.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btCollisionWorld.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btCollisionWorldImporter.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btGhostObject.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btHashedSimplePairCache.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btManifoldResult.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btSimulationIslandManager.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/btUnionFind.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionDispatch/SphereTriangleDetector.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btBox2dShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btBoxShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btCapsuleShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btCollisionShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btCompoundShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btConcaveShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btConeShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btConvex2dShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btConvexHullShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btConvexInternalShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btConvexPointCloudShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btConvexPolyhedron.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btConvexShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btCylinderShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btEmptyShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btMiniSDF.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btMinkowskiSumShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btMultiSphereShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btOptimizedBvh.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btSdfCollisionShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btShapeHull.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btSphereShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btStaticPlaneShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btStridingMeshInterface.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btTetrahedronShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btTriangleBuffer.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btTriangleCallback.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btTriangleMesh.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btTriangleMeshShape.cpp \
hsp3dish/extlib/src/BulletCollision/CollisionShapes/btUniformScalingShape.cpp \
hsp3dish/extlib/src/BulletCollision/Gimpact/btContactProcessing.cpp \
hsp3dish/extlib/src/BulletCollision/Gimpact/btGenericPoolAllocator.cpp \
hsp3dish/extlib/src/BulletCollision/Gimpact/btGImpactBvh.cpp \
hsp3dish/extlib/src/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.cpp \
hsp3dish/extlib/src/BulletCollision/Gimpact/btGImpactQuantizedBvh.cpp \
hsp3dish/extlib/src/BulletCollision/Gimpact/btGImpactShape.cpp \
hsp3dish/extlib/src/BulletCollision/Gimpact/btTriangleShapeEx.cpp \
hsp3dish/extlib/src/BulletCollision/Gimpact/gim_box_set.cpp \
hsp3dish/extlib/src/BulletCollision/Gimpact/gim_contact.cpp \
hsp3dish/extlib/src/BulletCollision/Gimpact/gim_memory.cpp \
hsp3dish/extlib/src/BulletCollision/Gimpact/gim_tri_collision.cpp \
hsp3dish/extlib/src/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.cpp \
hsp3dish/extlib/src/BulletCollision/NarrowPhaseCollision/btConvexCast.cpp \
hsp3dish/extlib/src/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.cpp \
hsp3dish/extlib/src/BulletCollision/NarrowPhaseCollision/btGjkEpa2.cpp \
hsp3dish/extlib/src/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.cpp \
hsp3dish/extlib/src/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp \
hsp3dish/extlib/src/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.cpp \
hsp3dish/extlib/src/BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp \
hsp3dish/extlib/src/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.cpp \
hsp3dish/extlib/src/BulletCollision/NarrowPhaseCollision/btRaycastCallback.cpp \
hsp3dish/extlib/src/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.cpp \
hsp3dish/extlib/src/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.cpp \
hsp3dish/extlib/src/BulletDynamics/Character/btKinematicCharacterController.cpp \
hsp3dish/extlib/src/BulletDynamics/ConstraintSolver/btBatchedConstraints.cpp \
hsp3dish/extlib/src/BulletDynamics/ConstraintSolver/btConeTwistConstraint.cpp \
hsp3dish/extlib/src/BulletDynamics/ConstraintSolver/btContactConstraint.cpp \
hsp3dish/extlib/src/BulletDynamics/ConstraintSolver/btFixedConstraint.cpp \
hsp3dish/extlib/src/BulletDynamics/ConstraintSolver/btGearConstraint.cpp \
hsp3dish/extlib/src/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.cpp \
hsp3dish/extlib/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpring2Constraint.cpp \
hsp3dish/extlib/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.cpp \
hsp3dish/extlib/src/BulletDynamics/ConstraintSolver/btHinge2Constraint.cpp \
hsp3dish/extlib/src/BulletDynamics/ConstraintSolver/btHingeConstraint.cpp \
hsp3dish/extlib/src/BulletDynamics/ConstraintSolver/btNNCGConstraintSolver.cpp \
hsp3dish/extlib/src/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.cpp \
hsp3dish/extlib/src/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.cpp \
hsp3dish/extlib/src/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolverMt.cpp \
hsp3dish/extlib/src/BulletDynamics/ConstraintSolver/btSliderConstraint.cpp \
hsp3dish/extlib/src/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.cpp \
hsp3dish/extlib/src/BulletDynamics/ConstraintSolver/btTypedConstraint.cpp \
hsp3dish/extlib/src/BulletDynamics/ConstraintSolver/btUniversalConstraint.cpp \
hsp3dish/extlib/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp \
hsp3dish/extlib/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorldMt.cpp \
hsp3dish/extlib/src/BulletDynamics/Dynamics/btRigidBody.cpp \
hsp3dish/extlib/src/BulletDynamics/Dynamics/btSimpleDynamicsWorld.cpp \
hsp3dish/extlib/src/BulletDynamics/Dynamics/btSimulationIslandManagerMt.cpp \
hsp3dish/extlib/src/BulletDynamics/Featherstone/btMultiBody.cpp \
hsp3dish/extlib/src/BulletDynamics/Featherstone/btMultiBodyConstraint.cpp \
hsp3dish/extlib/src/BulletDynamics/Featherstone/btMultiBodyConstraintSolver.cpp \
hsp3dish/extlib/src/BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.cpp \
hsp3dish/extlib/src/BulletDynamics/Featherstone/btMultiBodyFixedConstraint.cpp \
hsp3dish/extlib/src/BulletDynamics/Featherstone/btMultiBodyGearConstraint.cpp \
hsp3dish/extlib/src/BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.cpp \
hsp3dish/extlib/src/BulletDynamics/Featherstone/btMultiBodyJointMotor.cpp \
hsp3dish/extlib/src/BulletDynamics/Featherstone/btMultiBodyMLCPConstraintSolver.cpp \
hsp3dish/extlib/src/BulletDynamics/Featherstone/btMultiBodyPoint2Point.cpp \
hsp3dish/extlib/src/BulletDynamics/Featherstone/btMultiBodySliderConstraint.cpp \
hsp3dish/extlib/src/BulletDynamics/Featherstone/btMultiBodySphericalJointLimit.cpp \
hsp3dish/extlib/src/BulletDynamics/Featherstone/btMultiBodySphericalJointMotor.cpp \
hsp3dish/extlib/src/BulletDynamics/MLCPSolvers/btDantzigLCP.cpp \
hsp3dish/extlib/src/BulletDynamics/MLCPSolvers/btLemkeAlgorithm.cpp \
hsp3dish/extlib/src/BulletDynamics/MLCPSolvers/btMLCPSolver.cpp \
hsp3dish/extlib/src/BulletDynamics/Vehicle/btRaycastVehicle.cpp \
hsp3dish/extlib/src/BulletDynamics/Vehicle/btWheelInfo.cpp \
hsp3dish/extlib/src/LinearMath/btAlignedAllocator.cpp \
hsp3dish/extlib/src/LinearMath/btConvexHull.cpp \
hsp3dish/extlib/src/LinearMath/btConvexHullComputer.cpp \
hsp3dish/extlib/src/LinearMath/btGeometryUtil.cpp \
hsp3dish/extlib/src/LinearMath/btPolarDecomposition.cpp \
hsp3dish/extlib/src/LinearMath/btQuickprof.cpp \
hsp3dish/extlib/src/LinearMath/btReducedVector.cpp \
hsp3dish/extlib/src/LinearMath/btSerializer.cpp \
hsp3dish/extlib/src/LinearMath/btSerializer64.cpp \
hsp3dish/extlib/src/LinearMath/btThreads.cpp \
hsp3dish/extlib/src/LinearMath/btVector3.cpp \
hsp3dish/extlib/src/zlib/adler32.c \
hsp3dish/extlib/src/zlib/compress.c \
hsp3dish/extlib/src/zlib/crc32.c \
hsp3dish/extlib/src/zlib/deflate.c \
hsp3dish/extlib/src/zlib/gzclose.c \
hsp3dish/extlib/src/zlib/gzlib.c \
hsp3dish/extlib/src/zlib/gzread.c \
hsp3dish/extlib/src/zlib/gzwrite.c \
hsp3dish/extlib/src/zlib/inflate.c \
hsp3dish/extlib/src/zlib/infback.c \
hsp3dish/extlib/src/zlib/inftrees.c \
hsp3dish/extlib/src/zlib/inffast.c \
hsp3dish/extlib/src/zlib/trees.c \
hsp3dish/extlib/src/zlib/uncompr.c \
hsp3dish/extlib/src/zlib/zutil.c \
hsp3dish/extlib/src/libpng/png.c \
hsp3dish/extlib/src/libpng/pngerror.c \
hsp3dish/extlib/src/libpng/pngget.c \
hsp3dish/extlib/src/libpng/pngmem.c \
hsp3dish/extlib/src/libpng/pngpread.c \
hsp3dish/extlib/src/libpng/pngread.c \
hsp3dish/extlib/src/libpng/pngrio.c \
hsp3dish/extlib/src/libpng/pngrtran.c \
hsp3dish/extlib/src/libpng/pngrutil.c \
hsp3dish/extlib/src/libpng/pngset.c \
hsp3dish/extlib/src/libpng/pngtrans.c \
hsp3dish/extlib/src/libpng/pngwio.c \
hsp3dish/extlib/src/libpng/pngwrite.c \
hsp3dish/extlib/src/libpng/pngwtran.c \
hsp3dish/extlib/src/libpng/pngwutil.c

include $(BUILD_STATIC_LIBRARY)

