
//
//	errormsg.cpp header
//
#ifndef __errormsg_h
#define __errormsg_h

// error for CodeGenerator
typedef enum {
	CGERROR_NONE = 0,
	CGERROR_UNKNOWN,
	CGERROR_SYNTAX,
	CGERROR_FLOATEXP,
	CGERROR_CALCEXP,
	CGERROR_PRMEND,
	CGERROR_ARRAYEXP,
	CGERROR_LABELEXIST,
	CGERROR_LABELNAME,

	CGERROR_REPEAT_OVERFLOW,
	CGERROR_BREAK_WO_REPEAT,
	CGERROR_CONT_WO_REPEAT,
	CGERROR_LOOP_WO_REPEAT,
	CGERROR_LOOP_NOTFOUND,

	CGERROR_ELSE_WO_IF,
	CGERROR_BLOCK_NOT_CLOSED,
	CGERROR_BLOCKEXP,
	CGERROR_BAD_ELSE_EXP,
	CGERROR_IF_OVERFLOW,

	CGERROR_FATAL,

	CGERROR_PP_SYNTAX,
	CGERROR_PP_NO_REGCMD,
	CGERROR_PP_NAMEREQUIRED,
	CGERROR_PP_WRONG_PARAM_NAME,
	CGERROR_PP_NO_USELIB,
	CGERROR_PP_ALREADY_USE_FUNC,
	CGERROR_PP_ALREADY_USE_PARAM,
	CGERROR_PP_BAD_STRUCT_SOURCE,
	CGERROR_PP_BAD_STRUCT,
	CGERROR_PP_BAD_IMPORT_NAME,
	CGERROR_PP_ALREADY_USE_FUNCNAME,
	CGERROR_PP_INCOMPATIBLE_IMPORT,
	CGERROR_PP_MODINIT_USED,
	CGERROR_PP_MODTERM_USED,

	CGERROR_MULTILINE_STR,
	CGERROR_PP_ALREADY_USE_TAGNAME,
	CGERROR_PP_NO_USECOM,
	CGERROR_PP_BAD_IMPORT_INDEX,
	CGERROR_PP_BAD_IMPORT_IID,

	CGERROR_VAR_NOINIT,
	CGERROR_WRONG_VARIABLE,

	CGERROR_MAX,
} CGERROR;

char *cg_geterror( CGERROR error );


#endif
