//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Poppad.rc
//
#define IDOK2                           3
#define IDM_BUTTON1                     3
#define IDM_NEW                         1000
#define IDM_OPEN                        1001
#define IDM_SAVE                        1002
#define IDM_SAVEAS                      1003
#define IDM_SAVEALL                     1004
#define IDM_PRINT                       1005
#define IDM_EXIT                        1006
#define IDM_UNDO                        1100
#define IDM_REDO                        1101
#define IDM_CUT                         1102
#define IDM_COPY                        1103
#define IDM_PASTE                       1104
#define IDM_CLEAR                       1105
#define IDM_SELALL                      1106
#define IDM_LTOP                        1200
#define IDM_LBTM                        1201
#define IDM_JUMP                        1252
#define IDM_FIND                        1300
#define IDM_BACK                        1301
#define IDM_NEXT                        1302
#define IDM_REPLACE                     1303
#define IDM_FONT                        1400
#define IDM_BGCOLOR                     1401
#define IDM_VIEW_TOOLBAR                1402
#define IDM_VIEW_STATUS                 1403
#define IDM_HSCROLL                     1404
#define IDM_STARTDIR                    1405
#define IDM_COMP                        1500
#define IDM_RUN                         1501
#define IDM_COMP2                       1502
#define IDM_HSPERR                      1503
#define IDM_MKOBJ                       1504
#define IDM_MKOBJ2                      1505
#define IDM_AUTOMAKE                    1506
#define IDM_COMP3                       1507
#define IDM_LOGCOMP                     1508
#define IDM_HSPSYM                      1509
#define IDM_CMDOPT                      1510
#define IDM_FULLSCR                     1511
#define IDM_DEBUG                       1512
#define IDM_HSPEXTMACRO                 1513
#define IDM_HSPCLMODE                   1514
#define IDM_PACKED                      1600
#define IDM_PACKGO                      1601
#define IDM_MKEXE1                      1602
#define IDM_MKEXE2                      1603
#define IDM_START_RUNTIMEMAN            1604
#define IDM_OPEN_SRCFOLDER              1605
#define IDM_OPTION                      1606
#define IDM_CLOSEACT                    1700
#define IDM_CLOSEALL                    1701
#define IDM_CLOSEALEFT                  1702
#define IDM_CLOSEARIGHT                 1703
#define IDM_KWHELP                      1800
#define IDM_HELPDIR                     1801
#define IDM_HSPMAN1                     1802
#define IDM_HSPMAN2                     1803
#define IDM_HSPMAN3                     1804
#define IDM_ABOUT                       1805
#define IDM_OPENIME                     2000
#define IDM_RECONVERT                   2001
#define IDM_SAVETABAS                   2100
#define IDM_SAVETAB                     2101
#define IDM_CLOSE                       2102
#define IDM_CLOSELEFT                   2103
#define IDM_CLOSERIGHT                  2104
#define IDM_HELP                        2900
#define IDM_LABEL                       2901
#define IDM_NEXTTAB                     2902
#define IDM_PREVTAB                     2903
#define IDM_ZNEXTTAB                    2904
#define IDM_ZPREVTAB                    2905
#define IDM_DUMMY                       2910
#define IDM_RETURN                      2910
#define IDM_AHTMAN                      2915
#define IDM_AHT_RND                     2917
#define IDM_AHTFONT                     2919
#define IDM_AHTCOLOR                    2921
#define IDM_AHTTOOL                     2923
#define ID__DART                        2925
#define ID__DAAK                        2926
#define ID_2927                         2927
#define IDM_HSPTV                       2928
#define IDCM_ADD                        3000
#define IDCM_ALLSEL                     3001
#define IDCM_BYE                        3002
#define IDCM_CLR                        3003
#define IDCM_DEL                        3004
#define IDC_BUTTON1                     4000
#define IDC_BUTTON2                     4001
#define IDC_CDIR                        4002
#define IDC_BUTTON3                     4002
#define IDC_CHECK1                      4003
#define IDC_CHECK2                      4004
#define IDC_CHECK3                      4005
#define IDC_CHECK4                      4006
#define IDC_CHECK5                      4007
#define IDC_CHECK6                      4008
#define IDC_CHECK7                      4009
#define IDC_COMBO1                      4010
#define IDC_CHECK8                      4010
#define IDC_COMBO2                      4011
#define IDC_CHECK9                      4011
#define IDC_COMBO3                      4012
#define IDC_COMBO4                      4013
#define IDC_COMBO5                      4015
#define IDC_COMBO6                      4016
#define IDC_EDIT1                       4017
#define IDC_EDIT2                       4018
#define IDC_EDIT3                       4019
#define IDC_EDIT4                       4020
#define IDC_EDIT5                       4021
#define IDC_EDIT6                       4022
#define IDC_EDIT7                       4023
#define IDC_EDIT8                       4024
#define IDC_FAME                        4025
#define IDC_FINDMODE                    4026
#define IDC_FINDMODE1                   4027
#define IDC_FRAME                       4028
#define IDC_LIST1                       4029
#define IDC_LIST2                       4030
#define IDC_LIST3                       4031
#define IDC_ONLINE                      4032
#define IDC_ONURL                       4033
#define IDC_RADIO1                      4034
#define IDC_RADIO2                      4035
#define IDC_RADIO3                      4036
#define IDC_RADIO4                      4037
#define IDC_STATICLINK                  4038
#define IDC_RADIO5                      4038
#define IDC_SUBBOX                      4039
#define IDC_RADIO6                      4039
#define IDC_SUBJECT                     4040
#define IDC_SUBJECT2                    4041
#define IDC_SUBJECT3                    4042
#define IDC_TREE1                       4043
#define IDC_STATIC1                     4044
#define IDC_STATIC2                     4045
#define IDC_STATIC3                     4046
#define IDC_STATIC4                     4047
#define IDC_STATIC5                     4048
#define IDC_STATIC6                     4049
#define IDC_STATIC7                     4050
#define IDC_RADIO8                      4051
#define IDC_STATIC8                     4052
#define IDC_REF_CMDLINE                 4053
#define IDC_REF_WORKDIR                 4054
#define IDC_MOVE_UP                     4055
#define IDC_MOVE_DOWN                   4056
#define IDB_TOOLBAR                     5000
#define IDD_FNAME                       5000
#define IDB_BITMAP2                     5001
#define IDD_DIALOG1                     5001
#define IDI_ICON1                       5002
#define IDI_ICON2                       5003
#define IDD_DIALOG2                     5005
#define ID_5006                         5006
#define ID_5007                         5007
#define ID_5008                         5008
#define ID__5009                        5009
#define IDM_RELOAD                      6001
#define IDM_RELOADTAB                   6002
#define IDM_ACTIVATETAB                 10000
#define IDM_EXTTOOL                     20000
#define IDM_AHTEZINPUT                  30000
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        5010
#define _APS_NEXT_COMMAND_VALUE         2929
#define _APS_NEXT_CONTROL_VALUE         4057
#define _APS_NEXT_SYMED_VALUE           6003
#endif
#endif
